FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run

RUN apt-get update && \
  apt-get install python3-pip && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN pip3 install zeroconf

COPY discover.py /usr/src/app/discover.py
COPY ./start.sh /usr/src/app/start.sh

CMD ["/usr/src/app/start.sh"]
